### ISSUE TITLE
第1章 JavaScript不只是简单的构件块

### ISSUE THREAD

**Issue by yangtao2o** [yangtao2o/learninglog#9]
慕课网手记[归纳《JavaScript经典实例》之JS不只是简单的构件块](http://www.imooc.com/article/20555)
* [1.1 JavaScript对象、基本类型和字面值之间的区别](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-1)
* [1.2 从字符串提取一个列表](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-2)
* [1.3 检查一个存在的、非空的字符串](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-3)
* [1.4 插入特殊字符](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-4)
* [1.5 使用新字符串替换模式](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-5)
* [1.6 找到并突出显示一个模式的所有实例](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-6)
* [1.7 使用捕获圆括号交换一个字符串中的单词](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-7)
* [1.8 使用命名实体来替代HTML标签](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-8)
* [1.9 ISO 8610格式的日期转换为Date对象可接受的一种形式](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-9)
* [1.10 使用带有定时器的函数闭包](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-10)
* [1.11 记录两个事件之间消耗的时间](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-11)
* [1.12 十进制数转化为十六进制值](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-12)
* [1.13 想要将表中一列的所有数字加和](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-13)
* [1.14 在角度和弧度之间转换](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-14)
* [1.15 找到页面元素可容纳的一个圆的半径和圆心](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-15)
* [1.16 计算圆弧的长度](https://github.com/yizhehu/learninglog/wiki/JavaScript经典实例#1-16)

**Comment by yizhehu** [comment]
20170923,0924

**Comment by yizhehu** [comment]
增加绝对链接
